/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-24 22:15:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import board.model.vo.Board;
import java.util.Calendar;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import user.member.model.service.UserService;
import user.member.controller.*;
import user.vo.User;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1598281724000L));
    _jspx_dependants.put("/WEB-INF/views/common/userHeader.jsp", Long.valueOf(1598306330931L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("user.member.controller");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("user.vo.User");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("user.member.model.service.UserService");
    _jspx_imports_classes.add("board.model.vo.Board");
    _jspx_imports_classes.add("java.sql.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

	User memberLoggedIn = (User)session.getAttribute("memberLoggedIn");
    String adminGrade = UserService.USER_ADMIN;

	//쿠키확인 : 요청과 함께 전송된 쿠키확인
	boolean saveId = false;
	String userId = "";
	Cookie[] cookies = request.getCookies();
	if(cookies != null){
		for(Cookie c : cookies){
			String key = c.getName();
			String value = c.getValue();
			if("saveId".equals(key)){
				saveId = true;
				userId = value;
			}
		}
	}	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/header.css\" />\r\n");
      out.write(" <style>\r\n");
      out.write("\r\n");
      out.write(" </style>\r\n");
      out.write(" <script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("\t$(\"#user-login-form\").submit(function(){\r\n");
      out.write("\t\tvar $userId = $(\"#input-login-id\");\r\n");
      out.write("\t\tvar $password = $(\"#input-login-password\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(/^.{4,}$/.test($userId.val()) == false){\r\n");
      out.write("\t\t\talert(\"유효한 아이디를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\tif(/^.{4,}$/.test($password.val()) == false){\r\n");
      out.write("\t\t\talert(\"유효한 패스워드를 입력하세요.\");\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t        });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // 로그인 드롭다운 \r\n");
      out.write("        function mypage(){\r\n");
      out.write("            $(\"#mypage-login\").slideToggle();    \r\n");
      out.write("            $(\"#mypage-loggedIn\").slideToggle();    \r\n");
      out.write("        }\r\n");
      out.write("        // 비밀번호 변경 시 js 효과\r\n");
      out.write("/*         function lostPw(){\r\n");
      out.write("            $(\"#mypage-login\").slideUp();\r\n");
      out.write("            $(\"#mypage-lostpw\").slideDown('300', 'linear');\r\n");
      out.write("        }; */\r\n");
      out.write("        // 비밀번호 변경 시 정보 체크\r\n");
      out.write("        function infoChk(){\r\n");
      out.write("            var INFO = 1;\r\n");
      out.write("            if(INFO = 1){\r\n");
      out.write("                alert(\"비밀번호 변경이 완료되었습니다!\");\r\n");
      out.write("                 $(\"#mypage-lostpw\").slideUp();\r\n");
      out.write("                $(\"#mypage-lostpw\").css(\"display\", \"none.\");\r\n");
      out.write("                $(\"#mypage-login\").slideDown(); \r\n");
      out.write("\r\n");
      out.write("            }else{\r\n");
      out.write("                alert(\"입력하신 정보가 고객님의 회원 정보와 일치하지 않습니다.\\n다시 확인해 주세요.\");\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        $(function(){\r\n");
      out.write("        \t$(\"#logout\").click(function(){\r\n");
      out.write("        \t\t$(\"#mypage-login\").slideToggle();\r\n");
      out.write("        \t\t$(\"#mypage-loggedIn\").slideToggle();\r\n");
      out.write("        \t\tvar result = confirm(\"로그아웃 하시겠습니까?\");\r\n");
      out.write("            \tif(result){\r\n");
      out.write("            \t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/user/logout\";\r\n");
      out.write("            \t\talert(\"성공적으로 로그아웃 되었습니다!\");\r\n");
      out.write("            \t}\r\n");
      out.write("        \t});\r\n");
      out.write("        });\r\n");
      out.write("        function adminLogout(){\r\n");
      out.write("        \tvar result = confirm(\"로그아웃 하시겠습니까?\");\r\n");
      out.write("        \tif(result){\r\n");
      out.write("        \t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/user/logout\";\r\n");
      out.write("        \t\talert(\"성공적으로 로그아웃 되었습니다!\");\r\n");
      out.write("        \t}\r\n");
      out.write("        };\r\n");
      out.write("        //비밀번호 재설정\r\n");
      out.write("        function lostPw(){\r\n");
      out.write("        \tlocation.href = \"");
      out.print(request.getContextPath());
      out.write("/user/checkInfo\";\r\n");
      out.write("        \t\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        //리뷰팝업\r\n");
      out.write("\t        function writeReview(){\r\n");
      out.write("        \tvar url = \"");
      out.print(request.getContextPath());
      out.write("/user/writeReview\";\r\n");
      out.write("        \tvar title = \"WriteReviewPopup\";\r\n");
      out.write("        \tvar status = \"left=366px, top=100px, width=700px, height=450px\";\r\n");
      out.write("        \t\r\n");
      out.write("        \topen(url, title, status);\r\n");
      out.write("        }; \r\n");
      out.write("        \r\n");
      out.write("        function msg(){\r\n");
      out.write("        \tvar url = \"");
      out.print( request.getContextPath() );
      out.write("/user/message?userId=");
      out.print( memberLoggedIn != null ? memberLoggedIn.getUserId() : "" );
      out.write("\";\r\n");
      out.write("        \tvar title = \"My Message\";\r\n");
      out.write("        \tvar status = \"left= 300px, top=50px, width=1000px, height=700;\";\r\n");
      out.write("        \topen(url, title, status);\r\n");
      out.write("        };\r\n");
      out.write("    </script>\r\n");
      out.write("    <style>\r\n");
      out.write("\t  @font-face {\r\n");
      out.write("        font-family: 'IBMPlexSansKR-Regular';\r\n");
      out.write("        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Regular.woff') format('woff');\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-style: normal;\r\n");
      out.write("        }  \r\n");
      out.write("        html, body{\r\n");
      out.write("        font-family: 'IBMPlexSansKR-Regular';\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 회원이 현재 로그인하지 않은 경우, 즉 비회원인 경우 -->\r\n");
 if (memberLoggedIn == null){ 
      out.write("\t\r\n");
      out.write("    <div class=\"wrapper-user-header\">\r\n");
      out.write("        <div class=\"user-header\">\r\n");
      out.write("            <div class=\"user-navbar\">\r\n");
      out.write("                    <div class=\"navbar-user-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath());
      out.write("\"><button id=\"logo-btn\" class=\"logo-btn\">cooking-king</button></a>\r\n");
      out.write("            <button class=\"user-navbar1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">클래스</button>\r\n");
      out.write("            <button class=\"user-navbar2\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/schedule'\">내 스케줄</button>\r\n");
      out.write("            <button class=\"user-navbar4\" id=\"mypage-btn\" onclick=\"mypage();\">로그인</button>\r\n");
      out.write("            <button class=\"user-navbar5\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/center/list'\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       <div class=\"login-wrapper\">\r\n");
      out.write("            <div class=\"mypage-login\" id=\"mypage-login\">\r\n");
      out.write("                <p id=\"welcome-back\" class=\"welcome-back\">WELCOME!</p>\r\n");
      out.write("                <form class=\"user-login-form\" id=\"user-login-form\"\r\n");
      out.write("                action=\"");
      out.print( request.getContextPath() );
      out.write("/user/login\"\r\n");
      out.write("\t\t\t\t\t  method=\"POST\">\r\n");
      out.write("                    <input type=\"text\" class=\"input-login-id\" id=\"input-login-id\" name=\"userId\"\r\n");
      out.write("                        placeholder=\"아이디를 입력하세요.\" value=\"");
      out.print( saveId ? userId : "");
      out.write("\" required><br>\r\n");
      out.write("                    <input type=\"password\" class=\"input-login-password\" id=\"input-login-password\" name=\"password\"\r\n");
      out.write("                        placeholder=\"비밀번호를 입력하세요.\" required><br>\r\n");
      out.write("                        <a href=\"#\" id=\"lost-pw\" class=\"lost-pw-question\" onclick=\"lostPw();\">비밀번호를 잊으셨나요?</a>\r\n");
      out.write("                        <br />\r\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath());
      out.write("/user/enroll\" \r\n");
      out.write("                        id=\"register-q\" class=\"register-question\">또는 회원가입을 원하시나요?</a>\r\n");
      out.write("                        <br />\r\n");
      out.write("                    <input type=\"submit\" value=\"로그인\" id=\"login-btn\" class=\"login-btn\" onclick=\"login();\" required><br>\r\n");
      out.write("                </form>\r\n");
      out.write("           </div>\r\n");
      out.write("     </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 여기까지 확인 완료 -->\r\n");
      out.write("  ");
 } else if (memberLoggedIn != null && !memberLoggedIn.getCommGrade().equals(adminGrade)){ 
      out.write("\r\n");
      out.write("      <div class=\"wrapper-user-header\">\r\n");
      out.write("        <div class=\"user-header\">\r\n");
      out.write("            <div class=\"user-navbar\">\r\n");
      out.write("                    <div class=\"navbar-user-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath());
      out.write("\"><button id=\"logo-btn\" class=\"logo-btn\">cooking-king</button></a>\r\n");
      out.write("            <button class=\"user-navbar1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">클래스</button>\r\n");
      out.write("            <button class=\"user-navbar2\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/schedule?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("'\">내 스케줄</button>\r\n");
      out.write("            <button class=\"user-navbar4\" id=\"mypage-btn\" onclick=\"mypage();\">마이페이지</button>\r\n");
      out.write("            <button class=\"user-navbar5\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/center/list'\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("      <div class=\"mypage-loggedIn\" id=\"mypage-loggedIn\">\r\n");
      out.write("   \t\t<div class=\"hello\" id=\"hello\">\r\n");
      out.write("   \t\t\t<p class=\"hello-p\">");
      out.print( memberLoggedIn.getUserName() );
      out.write("님, 안녕하세요.</p>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("        <div class=\"mypage\" id=\"mypage\">\r\n");
      out.write("            <button class=\"mypages\" id=\"myinfo\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/user/view?userId=");
      out.print(memberLoggedIn.getUserId());
      out.write("'\">내 정보 수정</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"point-charge\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/point/pointManagement'\">포인트 관리</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"write-resume\" onclick=\"");
      out.print("P".equals(memberLoggedIn.getResumeYNP()) ? "alert('이력서심사가 진행중입니다.')" : "location.href='" +request.getContextPath()+ "/tutor/writerResume?userId=" +memberLoggedIn.getUserId()+"'" );
      out.write("\">이력서 관리</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"write-review\" onclick=\"writeReview();\">리뷰 작성</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"get-msg\" onclick=\"msg();\">메세지</button><br />\r\n");
      out.write("            <button class=\"mypages\" id=\"logout\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/member/logout'\">로그아웃</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>    \r\n");
      out.write("        ");
 } else if (memberLoggedIn != null && memberLoggedIn.getCommGrade().equals(adminGrade)){ 
      out.write("\r\n");
      out.write("    \t    <div class=\"wrapper-admin-header\">\r\n");
      out.write("       \t\t\t <div class=\"admin-header\">\r\n");
      out.write("          \t\t\t  <div class=\"admin-navbar\">\r\n");
      out.write("                    <div class=\"navbar-admin-menu\">\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath());
      out.write("\"><button id=\"logo-btn-a\">cooking-king</button></a>\r\n");
      out.write("            <button class=\"admin-navbar0\" id=\"admin-logout\" onclick=\"adminLogout();\">로그아웃</button>\r\n");
      out.write("            <button class=\"admin-navbar1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">클래스 관리</button>\r\n");
      out.write("            <button class=\"admin-navbar2\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/page'\">회원 관리</button>\r\n");
      out.write("            <button class=\"admin-navbar4\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/admin/analysis'\">현황 조회</button>\r\n");
      out.write("            <button class=\"admin-navbar5\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/center/list'\">고객센터</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("       \t\t\t <div class=\"helloAdmin\" id=\"helloAdmin\">\r\n");
      out.write("   \t\t\t\t\t<p class=\"helloAdmin-p\" onclick=\"adminLogout();\">\r\n");
      out.write("   \t\t\t\t\t");
      out.print( memberLoggedIn.getUserName() );
      out.write("님, 안녕하세요. </p>\r\n");
      out.write("   \t\t\t\t </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \t");
 } 
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("  \r\n");

	List<Board> list = (List<Board>)request.getAttribute("list");
	List<String> cList = new ArrayList<>();
	List<String> lList = new ArrayList<>();	
	String[] categoryArr = (String[])request.getParameterValues("category");
	if(categoryArr != null && categoryArr.length != 0){
		for(String s : categoryArr){
			cList.add(s);
		}
	}
	String[] locationArr = (String[])request.getParameterValues("location");
	if(locationArr != null && locationArr.length != 0){
		for(String s : locationArr){
			lList.add(s);
		}
	}
	String keywordType = (String)request.getParameter("keywordType");
	String keyword = (String)request.getParameter("keyword");
	
	String lowPriceS = request.getParameter("lowPrice");
	String highPriceS = request.getParameter("highPrice");
	int lowPrice = lowPriceS != null && !lowPriceS.isEmpty() ? Integer.parseInt(lowPriceS) : 0;
	int highPrice = highPriceS != null && !highPriceS.isEmpty() ? Integer.parseInt(highPriceS) : 0;
	
	String classDate = request.getParameter("classDate");
	
	Calendar cal = Calendar.getInstance();
	int now = cal.get(Calendar.YEAR);
	if(memberLoggedIn != null){
		cal.setTime(memberLoggedIn.getBirthday());
	}
	/* (예빈) 클래스 리스트 - 포인트 액수에 DecimalFormat 대입 */
	DecimalFormat pointF = new DecimalFormat("###,###,### 포인트");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/board-list.css\" />\r\n");
      out.write("<style>\r\n");
      out.write(" \t   .public-footer{\r\n");
      out.write("        top: 90em;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("/* \t\t$(\".search\").click(function(){\r\n");
      out.write("\t\t\t$(this).next(\"section\").slideToggle();\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\r\n");
      out.write("\t\t/* css 편의상 무식하게 바꿔부럿어요. 준혁시 미안해요 ㅎ; */\r\n");
      out.write("\t\t$(\"#class-s-btn1\").click(function(){\r\n");
      out.write("\t\t\t$(\"#search-category\").slideToggle();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#class-s-btn2\").click(function(){\r\n");
      out.write("\t\t\t$(\"#search-location\").slideToggle();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#class-s-btn3\").click(function(){\r\n");
      out.write("\t\t\t$(\"#search-price\").slideToggle();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#class-s-btn4\").click(function(){\r\n");
      out.write("\t\t\t$(\"#search-date\").slideToggle();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".priceInput\").keypress(function(event){\r\n");
      out.write("\t\t\tif (event.which && (event.which < 48 || event.which > 57)) {\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dateReset(){\r\n");
      out.write("\t\t$(\"[name=classDate]\").val(\"\");\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction gotoView(classNo, category){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(category == \"AL\"){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar msg;\r\n");
      out.write("\t\t\tmsg = \"미성년자는 이용하실 수 없습니다.\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(");
      out.print( memberLoggedIn == null );
      out.write("){\r\n");
      out.write("\t\t\t\tmsg += \"\\n로그인 후 이용해주세요.\";\r\n");
      out.write("\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(");
      out.print( now - cal.get(Calendar.YEAR) );
      out.write(" <= 19){\r\n");
      out.write("\t\t\t\talert(msg);\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/board/view?classNo=' + classNo;\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openClass(){\r\n");
      out.write("\t\t//로그인한 사람의 이력서 여부 확인 \r\n");
      out.write("\t\t//Y = 진행 / N = 이력서를 먼저 등록해주세요 / P = 아직 이력서 심사중입니다.\r\n");
      out.write("\t\tif(");
      out.print( memberLoggedIn == null );
      out.write("){\r\n");
      out.write("\t\t\talert(\"로그인 후 이용 가능한 기능 입니다.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\telse if(");
      out.print( memberLoggedIn != null && "N".equals(memberLoggedIn.getResumeYNP()) );
      out.write(") {\r\n");
      out.write("\t\t\talert(\"이력서를 먼저 등록해주세요.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(");
      out.print( memberLoggedIn != null && "P".equals(memberLoggedIn.getResumeYNP()) );
      out.write(") {\r\n");
      out.write("\t\t\talert(\"아직 이력서 심사가 진행중입니다.\");\r\n");
      out.write("\t\t\treturn\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href = \"");
      out.print( request.getContextPath() );
      out.write("/board/insert\";\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"class-list-wrapper\">\r\n");
      out.write("<p class=\"class-list-title\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/board/list'\">\r\n");
      out.write("\t<!-- (예빈) 클래스 관리 : 관리자 권한을 가진 로그인 사용자에게만 클래스 삭제 버튼을 노출한다.\r\n");
      out.write("\t\t   단, 클래스 list가 아닌 클래스 view단에서 처리하는 것으로 한다. (관리자라 하더라도 글을 삭제하기 전에 게시글 내용을 확인해야 하므로) -->\r\n");
      out.print( memberLoggedIn != null && memberLoggedIn.getCommGrade().equals(adminGrade) ? "클래스 관리" : "클래스 리스트" );
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\t<form class=\"class-list-form\" action=\"");
      out.print( request.getContextPath() );
      out.write("/board/list\"\r\n");
      out.write("\t\t  method=\"get\">\r\n");
      out.write("\t\t<div id=\"board-search\">\r\n");
      out.write("\t\t\t<div class=\"search\" id=\"class-search-buttons\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"카테고리 선택\" class=\"class-search-btn\" id=\"class-s-btn1\"/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"지역 선택\" class=\"class-search-btn\" id=\"class-s-btn2\"/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"가격대 선택\" class=\"class-search-btn\" id=\"class-s-btn3\"/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"수업일 선택\" class=\"class-search-btn\" id=\"class-s-btn4\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<section class=\"search-sec\" id=\"search-category\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"category\" id=\"MD\" value=\"MD\" ");
      out.print( cList.contains("MD") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"MD\">본 요리 (Main Dish)</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"category\" id=\"DS\" value=\"DS\" ");
      out.print( cList.contains("DS") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"DS\">제과/제빵 (Dessert)</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"category\" id=\"DR\" value=\"DR\" ");
      out.print( cList.contains("DR") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"DR\">음료 (Drinks)</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"category\" id=\"AL\" value=\"AL\" ");
      out.print( cList.contains("AL") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"AL\">주류 (Liquors)</label>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<section class=\"search-sec\" id=\"search-location\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"location\" id=\"SOUTH\" value=\"SOUTH\" ");
      out.print( lList.contains("SOUTH") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"SOUTH\">강남구</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"location\" id=\"NORTH\" value=\"NORTH\" ");
      out.print( lList.contains("NORTH") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"NORTH\">강북구</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"location\" id=\"EAST\" value=\"EAST\" ");
      out.print( lList.contains("EAST") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"EAST\">강동구</label>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"location\" id=\"WEST\" value=\"WEST\" ");
      out.print( lList.contains("WEST") ? "checked" : "" );
      out.write("/>\r\n");
      out.write("\t\t\t\t<label for=\"WEST\">강서구</label>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<section class=\"search-sec\" id=\"search-price\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"priceInput\" name=\"lowPrice\" id=\"low\" style=\"text-align: center;\" placeholder=\"최소가격(생략가능)\" value=\"");
      out.print( lowPrice != 0 ? lowPrice : "" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<p class=\"cla-won\">원</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"from-to\">~</p>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"priceInput\" name=\"highPrice\" id=\"high\" style=\"text-align: center;\" placeholder=\"최대가격(생략가능)\" value=\"");
      out.print( highPrice != 0 ? highPrice : "" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<p class=\"cla-won\">원</p>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<section class=\"search-sec\" id=\"search-date\">\r\n");
      out.write("\t\t\t\t<input type=\"date\" name=\"classDate\" value=\"");
      out.print( classDate != null && !"".equals(classDate) ? classDate : "" );
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"초기화\" onclick=\"dateReset();\" class=\"cla-reset-btn\"/>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"keyword-sec\" id=\"keyword-sec\">\r\n");
      out.write("\t\t\t\t<select name=\"keywordType\" id=\"keywordType\">\r\n");
      out.write("\t\t\t\t\t<option value=\"title\" ");
      out.print( keywordType != null && !keywordType.isEmpty() && keywordType.equals("title") ? "selected" : "" );
      out.write(">제목</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"class_content\" ");
      out.print( keywordType != null && !keywordType.isEmpty() && keywordType.equals("class_content") ? "selected" : "" );
      out.write(">내용</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"user_name\" ");
      out.print( keywordType != null && !keywordType.isEmpty() && keywordType.equals("user_name") ? "selected" : "" );
      out.write(">튜터 이름</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"keyword\" id=\"keyword\" value=\"");
      out.print( keyword != null && !keyword.isEmpty() ? keyword : "" );
      out.write("\" placeholder=\"키워드를 입력해 주세요.\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"검색하기\" class=\"execute-search\"/>\r\n");
      out.write("\t\t<div class=\"open-pls\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"클래스 개설하기\" onclick=\"openClass();\" class=\"open-class-btn\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"board-class-list\">\r\n");
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"board-outer-class\">\r\n");
 
	if(list != null && !list.isEmpty()){ 
		for(Board b : list){

      out.write(" \t\r\n");
      out.write(" <div class=\"img-class-wrapper\"> \r\n");
      out.write("\t\t<!-- (예빈) 신청이 마감된 경우: 해당 섹션을 100% 흑백  + 105% 컨트라스트 처리하며, 수업료 항목을  \"신청이 마감되었습니다!\":black으로 대체한다. \r\n");
      out.write("\t\t\t   단, 신청이 마감된 경우 선언될 inline-style 속성은 복수가 될 것이고 (background-image, filter) \r\n");
      out.write("\t\t\t   그렇지 않은 경우 단수로 처리(background-image, NO FILTER)해야 하므로  문법에 맞추기 위해 else절 또한 함께 사용한다. \r\n");
      out.write("\t\t\t   문법에 맞게 작성한 경우 filter 선언문에 노란 줄이 쳐지는 것이 정상임. -->\r\n");
      out.write("\t\t\t<section class=\"cla-li-sec\" \r\n");
      out.write("\t\t\t\t\t style='background-image: url(\"");
      out.print( request.getContextPath() );
      out.write("/upload/food/");
      out.print( b.getClassPic1Ren() );
      out.write("\")\r\n");
      out.write("\t\t\t\t\t ");
 if(b.getApplyExpireYn().equals("N")) { 
      out.write("' \r\n");
      out.write("\t\t\t\t\t ");
 } else { 
      out.write("; filter: grayscale(100%) contrast(105%)' ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t onclick=\"gotoView(");
      out.print( b.getClassNo() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( b.getCategory() );
      out.write("');\" id=\"class-li-pics\">\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t <div class=\"class-list-info\">\r\n");
      out.write("\t\t\t\t<p class=\"cla-li-title\">");
      out.print( b.getTitle() );
      out.write("</p>\r\n");
      out.write("\t\t\t\t<p class=\"cla-li-tutor\"> &nbsp;");
      out.print( b.getTutorName() );
      out.write("&nbsp;튜터&nbsp;</p>\r\n");
      out.write("\t\t\t\t<p class=\"cla-li-price\" ");
 if(b.getApplyExpireYn().equals("Y")) { 
      out.write(" style='color: black; font-size: 0.8; letter-spacing: 1px'");
} 
      out.write(">\r\n");
      out.write("\t\t\t\t");
      out.print( b.getApplyExpireYn().equals("N") ? pointF.format(b.getPrice()) : "신청이 마감되었습니다!" );
      out.write("</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write(" \t</div> \r\n");
 
		}
	} else {

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t참여가능한 클래스가 존재 하지 않습니다.\r\n");
      out.write("\r\n");
 	} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"board-pageBar\">\r\n");
      out.write("\t\t<p id=\"pagebar\">");
      out.print( request.getAttribute("pageBar") );
      out.write("</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        @font-face {\r\n");
      out.write("            font-family: 'IBMPlexSansKR-Text';\r\n");
      out.write("            src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_20-07@1.0/IBMPlexSansKR-Text.woff') format('woff');\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* (예빈)고정 높이 footer: 각 페이지마다 그 높이가 다르므로 top 설정 style은 각 페이지에서 직접 제어하는 것으로 한다. */\r\n");
      out.write("        .public-footer{\r\n");
      out.write("        \tposition: absolute;\r\n");
      out.write("            padding-top: 1.6em;\r\n");
      out.write("            padding-bottom: 1.6em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            vertical-align: center;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            font-size: .86em;\r\n");
      out.write("            color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("            box-shadow: 0.5rem 0.5rem 0.5rem #BCC6D2, \r\n");
      out.write("            -0.5rem -0.5rem 0.5rem rgba(244, 249, 255, 0.726);\r\n");
      out.write("        \tborder-radius: 3rem;\r\n");
      out.write("            background-color: rgb(204, 219, 238);\r\n");
      out.write("        }\r\n");
      out.write("        .footer-inner{\r\n");
      out.write("            width: 114em;\r\n");
      out.write("            height: 10em;\r\n");
      out.write("        }\r\n");
      out.write("        .logo-title{\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 1.2em;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"public-footer\">\r\n");
      out.write("        <p class=logo-title>Cookingking </p>\r\n");
      out.write("            <div class=\"footer-inner\">\r\n");
      out.write("            <p class=\"first-line\">\r\n");
      out.write("                <strong>상호명</strong> \r\n");
      out.write("                    주식회사 Cookingking\r\n");
      out.write("                <strong>개인정보책임자</strong> \r\n");
      out.write("                    김동현\r\n");
      out.write("                <strong>사업자등록번호</strong> \r\n");
      out.write("                    111-11-11111\r\n");
      out.write("                <strong>통신판매신고번호</strong> \r\n");
      out.write("                    2020-서울강남-0825\r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"second-line\">\r\n");
      out.write("                <strong>주소</strong> \r\n");
      out.write("                    서울특별시 강남구 테헤란로 10길 9 그랑프리빌딩 5F\r\n");
      out.write("                <strong>대표번호</strong> \r\n");
      out.write("                    0000-0000\r\n");
      out.write("                <strong>이메일</strong>\r\n");
      out.write("                    we_love_cookingking@ckk.com \r\n");
      out.write("            </p>\r\n");
      out.write("            <p class=\"third-line\">\r\n");
      out.write("                <strong>(주)Cookingking</strong>\r\n");
      out.write("                    은 통신판매중개자이며 통신판매 당사자가 아닙니다. \r\n");
      out.write("                    따라서 클래스/개인간 거래 및 판매에 대하여 책임을 지지 않습니다.\r\n");
      out.write("            </p>        \r\n");
      out.write("            <p class=\"last-line\">\r\n");
      out.write("            <strong>Copyright © Cookingking. All Rights Reserved.</strong>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
